server:
  port: 8080
spring:
  application:
    name: service-provider
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.124.134:1521:helowin
    username: zhk
    password: zhk
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
mybatis:
  type-aliases-package: com.zhk.provider.pojo